name: custom_lints_map
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  analyzer: ^5.0.0
  custom_lint_builder: ^0.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
